version: '3.1'
services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    hostname: adminer
    ports:
      - 8080:8080
      
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data
    deploy:
      resources:
        limits:
          memory: 500m
    
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    hostname: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    deploy:
      resources:
        limits:
          memory: 200m

  nifi:
    image: apache/nifi
    restart: always
    container_name: nifi
    hostname: nifi
    volumes:
      - ./data/nifi:/opt/nifi/nifi-current/flowfile_repository
      - ./data/util:/util
    environment:
      NIFI_WEB_HTTP_PORT: "9090"
    ports:
      - "9090:9090"
      - "8443:8443"
    deploy:
      resources:
        limits:
          memory: 500m

  cassandra:
    image: cassandra
    restart: always
    container_name: cassandra
    hostname: cassandra
    expose:
    - 9042

  # cassandra-web:
  #   image: markusgulden/cassandra-web
  #   container_name: cassandra-web
  #   hostname: cassandra-web
  #   depends_on:
  #   - cassandra
  #   environment:
  #     CASSANDRA_HOST_IPS: 172.19.0.3
  #     CASSANDRA_PORT: 9042
  #     CASSANDRA_USER: cassandra
  #     CASSANDRA_PASSWORD: cassandra
  #   ports:
  #   - 3000:3000
