CREATE DATABASE IF NOT EXISTS SalesHubDB;

USE SalesHubDB;

CREATE TABLE IF NOT EXISTS  Customers
(
    `IDCustomer` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `Name` VARCHAR(150) NOT NULL,
    `Address` VARCHAR(200) NULL,
    `CEP` VARCHAR(8) NULL,
    `Email` VARCHAR(150) NULL,
    `Phone` VARCHAR(15) NULL,
    `RegisterDate` DATETIME NOT NULL,
    `Active` SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Orders
(
    `IDOrder` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `CustomerID` INTEGER NOT NULL,
    `Address` VARCHAR(200) NOT NULL,
    `CEP` VARCHAR(8) NOT NULL,
    `RegisterDate` DATETIME NOT NULL,
    `Active` SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItems
(
    `IDOrderItem` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `OrderID` INTEGER NOT NULL,
    `ProductID` INTEGER NOT NULL,
    `Quantity` DECIMAL(18, 2) NOT NULL,
    `UnitValue` DECIMAL(18, 2) NOT NULL,
    `TotalValue` DECIMAL(18, 2) NOT NULL,
    `RegisterDate` DATETIME NOT NULL,
    `Active` SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS  Products
(
    `IDProduct` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `Code` VARCHAR(8) NOT NULL,
    `Name` VARCHAR(150) NOT NULL,
    `Model` VARCHAR(30) NULL,
    `Manufacturer` VARCHAR(150) NULL,
    `Color` JSON NULL,
    `Size` JSON NULL,
    `RegisterDate` DATETIME NOT NULL,
    `Active` SMALLINT NOT NULL
);
