CREATE DATABASE IF NOT EXISTS Finance;

USE Finance;

CREATE TABLE IF NOT EXISTS ExchangeRate
(
    `IDExchangeRate` INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `Code` VARCHAR(3) NOT NULL,
    `CodeIn` VARCHAR(3) NOT NULL,
    `High` DECIMAL(18, 4) NOT NULL,
    `Low` DECIMAL(18, 4) NOT NULL,
    `Ask` DECIMAL(18, 4) NOT NULL,
    `RegisterDate` DATETIME NOT NULL,
    `Active` SMALLINT NOT NULL
);
